import { FormConfig } from '@/types/form';

export const formRegistrasiDataDiri: FormConfig = {
  id: 1,
  name: 'Form Registrasi Data Diri',
  description: 'Formulir registrasi data diri dengan dynamic field rendering, tree dependency, dan conditional mandatory validation.',
  status: 'active',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  fields: [
    {
      id: 1,
      parent_id: null,
      name: 'nama_lengkap',
      label: 'Nama Lengkap',
      type: 'free_text',
      required: true,
      sort_order: 1,
      placeholder: 'Masukkan nama lengkap sesuai KTP / Identitas',
      help_text: 'Wajib diisi sesuai kartu identitas resmi',
      grid_span: 2,
    },
    {
      id: 2,
      parent_id: null,
      name: 'jenis_kelamin',
      label: 'Jenis Kelamin',
      type: 'option',
      required: true,
      sort_order: 2,
      help_text: 'Pilih salah satu jenis kelamin',
      grid_span: 2,
      options: [
        {
          id: 201,
          field_id: 2,
          label: 'Laki-laki',
          value: 'laki_laki',
          sort_order: 1,
          status: 'active',
        },
        {
          id: 202,
          field_id: 2,
          label: 'Perempuan',
          value: 'perempuan',
          sort_order: 2,
          status: 'active',
        },
      ],
    },
    {
      id: 3,
      parent_id: null,
      name: 'status_pernikahan',
      label: 'Status Pernikahan',
      type: 'select',
      required: true,
      sort_order: 3,
      placeholder: '-- Pilih Status Pernikahan --',
      help_text: 'Pilih status pernikahan Anda saat ini',
      grid_span: 1,
      options: [
        {
          id: 301,
          field_id: 3,
          label: 'Belum Menikah',
          value: 'belum_menikah',
          sort_order: 1,
          status: 'active',
        },
        {
          id: 302,
          field_id: 3,
          label: 'Menikah',
          value: 'menikah',
          sort_order: 2,
          status: 'active',
        },
      ],
    },
    {
      id: 4,
      parent_id: 3,
      name: 'nama_pasangan',
      label: 'Nama Pasangan',
      type: 'free_text',
      required: false,
      sort_order: 4,
      placeholder: 'Masukkan nama lengkap pasangan...',
      help_text: 'Wajib diisi jika status pernikahan Menikah',
      grid_span: 1,
      rules: [
        {
          id: 401,
          field_id: 4,
          source_field_id: 3,
          operator: 'equals',
          value: 'menikah',
          action: 'show',
        },
        {
          id: 402,
          field_id: 4,
          source_field_id: 3,
          operator: 'equals',
          value: 'menikah',
          action: 'required',
        },
      ],
    },
    {
      id: 5,
      parent_id: null,
      name: 'pekerjaan',
      label: 'Pekerjaan',
      type: 'select',
      required: true,
      sort_order: 5,
      placeholder: '-- Pilih Pekerjaan --',
      help_text: 'Pilih jenis profesi / aktivitas pekerjaan utama',
      grid_span: 1,
      options: [
        {
          id: 501,
          field_id: 5,
          label: 'Pelajar / Mahasiswa',
          value: 'pelajar_mahasiswa',
          sort_order: 1,
          status: 'active',
        },
        {
          id: 502,
          field_id: 5,
          label: 'Karyawan',
          value: 'karyawan',
          sort_order: 2,
          status: 'active',
        },
        {
          id: 503,
          field_id: 5,
          label: 'Wiraswasta',
          value: 'wiraswasta',
          sort_order: 3,
          status: 'active',
        },
        {
          id: 504,
          field_id: 5,
          label: 'Lainnya',
          value: 'lainnya',
          sort_order: 4,
          status: 'active',
        },
      ],
    },
    {
      id: 6,
      parent_id: 5,
      name: 'nama_perusahaan_instansi',
      label: 'Nama Perusahaan / Instansi',
      type: 'free_text',
      required: false,
      sort_order: 6,
      placeholder: 'Masukkan nama sekolah, universitas, atau instansi perusahaan...',
      help_text: 'Wajib diisi jika pekerjaan Karyawan atau Pelajar / Mahasiswa',
      grid_span: 1,
      rules: [
        {
          id: 601,
          field_id: 6,
          source_field_id: 5,
          operator: 'equals',
          value: 'karyawan',
          action: 'show',
        },
        {
          id: 602,
          field_id: 6,
          source_field_id: 5,
          operator: 'equals',
          value: 'karyawan',
          action: 'required',
        },
        {
          id: 603,
          field_id: 6,
          source_field_id: 5,
          operator: 'equals',
          value: 'pelajar_mahasiswa',
          action: 'show',
        },
        {
          id: 604,
          field_id: 6,
          source_field_id: 5,
          operator: 'equals',
          value: 'pelajar_mahasiswa',
          action: 'required',
        },
      ],
    },
    {
      id: 7,
      parent_id: 5,
      name: 'pekerjaan_lainnya',
      label: 'Pekerjaan Lainnya',
      type: 'free_text',
      required: false,
      sort_order: 7,
      placeholder: 'Sebutkan jenis pekerjaan / aktivitas Anda...',
      help_text: 'Wajib diisi jika memilih opsi Pekerjaan Lainnya',
      grid_span: 1,
      rules: [
        {
          id: 701,
          field_id: 7,
          source_field_id: 5,
          operator: 'equals',
          value: 'lainnya',
          action: 'show',
        },
        {
          id: 702,
          field_id: 7,
          source_field_id: 5,
          operator: 'equals',
          value: 'lainnya',
          action: 'required',
        },
      ],
    },
    {
      id: 8,
      parent_id: null,
      name: 'alamat',
      label: 'Alamat',
      type: 'free_text',
      required: true,
      sort_order: 8,
      placeholder: 'Masukkan alamat tempat tinggal / domisili lengkap...',
      help_text: 'Wajib diisi alamat domisili lengkap',
      grid_span: 2,
    },
    {
      id: 9,
      parent_id: null,
      name: 'keterangan_tambahan',
      label: 'Keterangan Tambahan',
      type: 'free_text',
      required: false,
      sort_order: 9,
      placeholder: 'Catatan tambahan atau informasi pendukung lainnya (opsional)...',
      help_text: 'Opsional',
      grid_span: 2,
    },
  ],
};

export const initialFormsData: FormConfig[] = [formRegistrasiDataDiri];
